INSERT INTO PRODUCT(id, name , description, illustration, price) values
(0, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/300/300', 150),
(1, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/301/300', 150),
(2, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/302/300', 150),
(3, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/303/300', 150),
(4, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/304/300', 150),
(5, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/305/300', 150),
(6, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/306/300', 150),
(7, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/307/300', 150),
(8, 'Nom de produit', 'DESCRIPTION : Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.', 'https://picsum.photos/308/300', 150);
